translator: translator.cpp
	g++ translator.cpp -o translator

option_b: option_b.cpp
	g++ option_b.cpp -o option_b

option_a: option_a.cpp
	g++ option_a.cpp -o option_a

files_3: files_3.cpp
	g++ files_3.cpp -o files_3

files_2: files_2.cpp
	g++ files_2.cpp -o files_2

files_1.5: files_1.5.cpp
	g++ files_1.5.cpp -o files_1.5

files_1: files_1.cpp
	g++ files_1.cpp -o files_1

